### ISSUE TITLE
"EOFError: Ran out of input" during Compute Network Stats

### ISSUE THREAD

**Issue by Sankalpsp21** [CAnBioNet/TkNA#10]
I'm getting an error while running the step "compute_network_stats.py"
<img width="541" alt="image" src="https://user-images.githubusercontent.com/79608516/221714052-39d81418-530f-4bbe-b98c-0ec61d37bd2a.png">

Here are the command and files I used for this step:

"python random_networks/compute_network_stats.py --networks-file nashOutput/networkOutput/all_random_nws.pickle --bibc-groups node_types --bibc-calc-type rbc --stats-file all_rand_network_results.pickle --node-map /nfs3/PHARM/Morgun_Lab/amanda/network_analysis_NWcode/network_calculations/nash_2-23-23/input_2/nash_type_map.csv --node-groups plasma_anthro lipid_metab"

[nash_type_map.csv](https://github.com/CAnBioNet/network_calculations/files/10845226/nash_type_map.csv)

[all_rand_network_results.pickle](https://drive.google.com/file/d/1gNuHXg246MnB3EwKlEFLbVeEZJkOAumh/view?usp=sharing)

**Comment by bruceamm** [comment]
I'm running into the same issue. We are attempting to create large random networks of 6101 nodes and 108858 edges.

Traceback (most recent call last):
  File "/nfs3/PHARM/Morgun_Lab/amanda/network_analysis_NWcode/network_calculations/random_networks/create_random_networks.py", line 95, in <module>
    pickle.dump(networks, networksFile)
_pickle.PicklingError: memo id too large for LONG_BINGET
Traceback (most recent call last):
  File "/nfs3/PHARM/Morgun_Lab/amanda/network_analysis_NWcode/network_calculations/random_networks/compute_network_stats.py", line 129, in <module>
    networks = pickle.load(networksFile)
EOFError: Ran out of input
Traceback (most recent call last):
  File "/nfs3/PHARM/Morgun_Lab/amanda/network_analysis_NWcode/network_calculations/random_networks/synthesize_network_stats.py", line 35, in <module>
    args = getArgs()
  File "/nfs3/PHARM/Morgun_Lab/amanda/network_analysis_NWcode/network_calculations/random_networks/synthesize_network_stats.py", line 20, in getArgs
    raise Exception("Specified network stats file does not exist")
Exception: Specified network stats file does not exist

**Comment by newmanno** [comment]
This is likely a memory issue, as it only seems to happen with large networks. We will look into this more.
