### ISSUE TITLE
FloatingPointError, run_on_subsamples.py, nested-subsampling

### ISSUE THREAD

**Issue by bruceamm** [CAnBioNet/TkNA#29]
Error:
Traceback (most recent call last):
  File "run_on_subsamples.py", line 70, in <module>
    results = network_reconstructor.reconstructNetwork(config, subsampledData)
  File "/nfs3/PHARM/Morgun_Lab/amanda/network_analysis_NWcode/network_calculations/TkNA/reconstruction/reconstruction/NetworkReconstructorSingleCell.py", line 531, in reconstructNetwork
    return self.runPipeline(stages, allData, **kwargs)
  File "/nfs3/PHARM/Morgun_Lab/amanda/network_analysis_NWcode/network_calculations/TkNA/reconstruction/reconstruction/NetworkReconstructor.py", line 22, in runPipeline
    stage(allData)
  File "/nfs3/PHARM/Morgun_Lab/amanda/network_analysis_NWcode/network_calculations/TkNA/reconstruction/reconstruction/NetworkReconstructorSingleCell.py", line 500, in stageComputeCorrelations
    allData["correlationCoefficients"], allData["correlationPValues"] = calculateCorrelations(config, allData["filteredData"])
  File "/nfs3/PHARM/Morgun_Lab/amanda/network_analysis_NWcode/network_calculations/TkNA/reconstruction/reconstruction/NetworkReconstructorSingleCell.py", line 310, in calculateCorrelations
    correlationResults = treatmentData.groupby("metatreatment").map(calculateForMetatreatment)
  File "/home/pharmacy/bruceam/miniconda3/envs/python_nw_test_bruce_2/lib/python3.8/site-packages/xarray/core/groupby.py", line 795, in map
    return self._combine(applied, shortcut=shortcut)
  File "/home/pharmacy/bruceam/miniconda3/envs/python_nw_test_bruce_2/lib/python3.8/site-packages/xarray/core/groupby.py", line 819, in _combine
    combined = concat(applied, dim)
  File "/home/pharmacy/bruceam/miniconda3/envs/python_nw_test_bruce_2/lib/python3.8/site-packages/xarray/core/concat.py", line 238, in concat
    return f(
  File "/home/pharmacy/bruceam/miniconda3/envs/python_nw_test_bruce_2/lib/python3.8/site-packages/xarray/core/concat.py", line 427, in _dataset_concat
    datasets = list(datasets)
  File "/home/pharmacy/bruceam/miniconda3/envs/python_nw_test_bruce_2/lib/python3.8/site-packages/xarray/core/groupby.py", line 794, in <genexpr>
    applied = (maybe_wrap_array(arr, func(arr, *args, **kwargs)) for arr in grouped)
  File "/nfs3/PHARM/Morgun_Lab/amanda/network_analysis_NWcode/network_calculations/TkNA/reconstruction/reconstruction/NetworkReconstructorSingleCell.py", line 272, in calculateForMetatreatment
    methodKwargs, endArgs = methodPrepare(treatmentData)
  File "/nfs3/PHARM/Morgun_Lab/amanda/network_analysis_NWcode/network_calculations/TkNA/reconstruction/reconstruction/NetworkReconstructorSingleCell.py", line 237, in prepareSpearman
    spearmanKwargs["coefficient"] = 6.0 / (n * (numpy.square(n) - 1))
FloatingPointError: divide by zero encountered in true_divide

Command used:
python3 run_on_subsamples.py --data-file /nfs3/PHARM/Morgun_Lab/amanda/network_analysis_NWcode/network_calculations/TkNA/single_cell_test_5-10-23/cd206-gata3-treg/output/all_data_and_metadata.cdf --config-file /nfs3/PHARM/Morgun_Lab/amanda/network_analysis_NWcode/network_calculations/TkNA/single_cell_test_5-10-23/cd206-gata3-treg/config.json --subsample-file /nfs3/PHARM/Morgun_Lab/amanda/network_analysis_NWcode/network_calculations/TkNA/single_cell_test_5-10-23/cd206-gata3-treg/output/cd206-gata3-treg_subsample.json --output-file /nfs3/PHARM/Morgun_Lab/amanda/network_analysis_NWcode/network_calculations/TkNA/single_cell_test_5-10-23/cd206-gata3-treg/output/cd206-gata3-treg.zip -s

**Comment by macovskym** [comment]
Unable to reproduce.
